### ISSUE TITLE
Backups are somehow much smaller than expected. Script works when I run it manually though

### ISSUE THREAD

**Issue by shinytreecko** [nicolaschan/minecraft-backup#13]
I have this in the backup.sh file

SERVER_WORLD="./world/" # Server world directory
BACKUP_DIRECTORY="/mnt/minecraft/ava" # Directory to save backups in
MAX_BACKUPS=128 # -1 indicates unlimited
DELETE_METHOD="thin" # Choices: thin, sequential, none; sequential: delete oldest; thin: keep last 24 hourly, last $
COMPRESSION_ALGORITHM="gzip" # Leave empty for no compression
COMPRESSION_FILE_EXTENSION=".gz" # Leave empty for no compression; Precede with a . (for example: ".gz")
COMPRESSION_LEVEL=3 # Passed to the compression algorithm
ENABLE_CHAT_MESSAGES=true # Tell players in Minecraft chat about backup status
PREFIX="Backing up the server!" # Shows in the chat message
DEBUG=false # Enable debug messages
SUPPRESS_WARNINGS=false # Suppress warnings
WINDOW_MANAGER="screen" # Choices: screen, tmux

This is in the backup directory where the script saves everything.
-rw-r--r-- 1 wes wes   20 Feb  1 00:00 2021-02-01_00-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 13:00 2021-02-01_13-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 14:00 2021-02-01_14-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 15:00 2021-02-01_15-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 16:00 2021-02-01_16-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 17:00 2021-02-01_17-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 18:00 2021-02-01_18-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 19:00 2021-02-01_19-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 20:00 2021-02-01_20-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 21:00 2021-02-01_21-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 22:00 2021-02-01_22-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  1 23:00 2021-02-01_23-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 00:00 2021-02-02_00-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 01:00 2021-02-02_01-00-02.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 02:00 2021-02-02_02-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 03:00 2021-02-02_03-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 04:00 2021-02-02_04-00-02.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 05:00 2021-02-02_05-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 06:00 2021-02-02_06-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 07:00 2021-02-02_07-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 08:00 2021-02-02_08-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 09:00 2021-02-02_09-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 10:00 2021-02-02_10-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 11:00 2021-02-02_11-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 12:00 2021-02-02_12-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 13:00 2021-02-02_13-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 14:00 2021-02-02_14-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 15:00 2021-02-02_15-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 16:00 2021-02-02_16-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 17:00 2021-02-02_17-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 18:00 2021-02-02_18-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 19:00 2021-02-02_19-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 20:00 2021-02-02_20-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 21:00 2021-02-02_21-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 22:00 2021-02-02_22-00-01.tar.gz
-rw-r--r-- 1 wes wes 474M Feb  2 22:58 2021-02-02_22-58-04.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  2 23:00 2021-02-02_23-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  3 00:00 2021-02-03_00-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  3 01:00 2021-02-03_01-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  3 02:00 2021-02-03_02-00-01.tar.gz
-rw-r--r-- 1 wes wes   20 Feb  3 03:00 2021-02-03_03-00-01.tar.gz
-rw-r--r-- 1 wes wes 843M Feb  3 03:18 2021-02-03_03-17-26.tar.gz

The size of the backups is much bigger when I run the script manually, but the hourly backups that are made with the script running from a crontab don't look like they would contain an actual backup. Do you know how to fix this?

Edit: removed the "insert code" part because it didn't save my returns and made it hard to read

**Comment by nicolaschan** [comment]
That's strange -- I haven't seen this before. Can you provide the crontab script and any logs from cron?

**Comment by shinytreecko** [comment]
Yeah I should've included that in the first comment, but this is the crontab script:
00 * * * * /home/wes/ava\ minecraft/backup.sh

The logs for the crontab said that my world directory doesn't exist, which doesn't make sense why it works when the script is run by a user instead of crontab. I changed `SERVER_WORLD="./world/"` to `SERVER_WORLD="world"` then ran the script manually and it seemed to work. I guess I'll see in about 35 minutes what crontab has to say when it attempts an hourly backup. Thank you for your help so far and I love the project.

**Comment by nicolaschan** [comment]
Thanks for those details. You probably need to provide the full path to the `world` directory. I assume you are running the script from your server directory when you run it manually, so the relative path would work. But cron does not run it from your server world directory so it requires the full path.

So instead of `"world"` you should put the full path given by `pwd` in your server directory. It would probably be something like:
```bash
SERVER_WORLD="/home/wes/ava\ minecraft/world"
```

**Comment by shinytreecko** [comment]
I tried that but still got an error, but I did end up fixing it by removing
spaces from the directory and using the full path. Thank you so much! I
also didn't know that about cron but it makes perfect sense now that you
mention it.

**Comment by nicolaschan** [comment]
Great! I'm glad you got it working. I'll look into the spaces issue.
