### ISSUE TITLE
Is it possible to use this with docker?

### ISSUE THREAD

**Issue by shinytreecko** [nicolaschan/minecraft-backup#16]
I'm using pterodactyl panel and it uses docker to manage containers for servers. If I'm running a server in a docker container, I can't specify a screen for the script to turn off autosaving and notify users about backups being made then enabling autosave once the backup is done. Is there a way around this?

**Comment by nicolaschan** [comment]
I recently updated the script to support [RCON](https://wiki.vg/RCON). You should be able to enable RCON for your Minecraft server and then use the backup script's options to tell it to use RCON. If it's in a docker container, you'll need to make sure you expose the RCON port. There's an example of using RCON in the README.

**Comment by shinytreecko** [comment]
Oh i'm reading the documentation and I'm wondering what you mean by the xxd command with RCON. I have the script set up successfully to my knowledge and it made a backup successfully at 6:00 PM but I don't think i have xxd.

**Comment by nicolaschan** [comment]
`xxd` is a command line tool that I use in the RCON connection part of the script. It's fairly common, so I wouldn't be surprised if your system already has it installed by default. If you need to install it, it should be fairly straightforward to do so with your distro's package manager (`apt-get`, `yum`, `pacman`, etc.).

To make sure RCON is actually working, check the output of the script and see if there are any errors/warnings related to the RCON connection. You could also check the server console there should be some logs related to RCON if it is connecting successfully. If you are in game and you see messages from the script (and you are using the `-c` option to print messages to chat), then it is definitely working.

**Comment by shinytreecko** [comment]
Oh i'm running it with crontab and setting arguments inside of the script's file instead of in the crontab. I think those logs get printed to /var/mail/<username>
Edit: when i do xxd help it says unrecognized command so that's why i don't think it's installed.

**Comment by nicolaschan** [comment]
Yeah, you'll need to install xxd for the RCON to work then. It should be easy to install with your distro's package manager.

Without a working connection to the server, it might still do backups and some may be fine but there's the potential for issues if an autosave happens while the backups are taking place.

Also I highly recommend checking the logs/output of the script which should alert you to any issues.

**Comment by shinytreecko** [comment]
wow i just realized i did xxd help instead of xxd -help so all is good thank you so much for your help!
