### ISSUE TITLE
Clarification: MAX_BACKUPS

### ISSUE THREAD

**Issue by cgmckeever** [nicolaschan/minecraft-backup#17]
Due to disk limitations, I was trying to reduce the number of backups to keep.

I set `-m 10` but then I [receive the error ](https://github.com/nicolaschan/minecraft-backup/blob/ccaf734df2ec031612bced1ee3ba087c27f6fddf/backup.sh#L337)

```
MAX_BACKUPS (10) is smaller than TOTAL_BLOCK_SIZE (70)
```

Wondering how the number of backups relates the the blocksize? I thought this setting would just reduce the existing backups. Thanks for the great utility.

**Comment by nicolaschan** [comment]
In this case block size refers to the blocks of sub-hourly (16), hourly (24), daily (30), and weekly backups. If you choose the thinning deletion policy with fewer than 70 backups, then you might not have representatives in each of these categories (in the case of 10, it might just keep the last 10, but I'm not sure). I recommend using the sequential deletion policy if you want to keep fewer than 70.

**Comment by cgmckeever** [comment]
Thanks .. this makes sense!
