### ISSUE TITLE
Option to not backup if no players online

### ISSUE THREAD

**Issue by SwiftWinds** [nicolaschan/minecraft-backup#23]
When the server is empty, there's usually no need to backup, since nothing much is happening. Would adding an option to not backup if no players are online be a possibility? Thanks a lot for considering my request.

**Comment by nicolaschan** [comment]
Thanks for the suggestion! Saving storage space when there are no changes is a good idea. 

It would not be as simple as checking if players are online. There are scenarios where you would want to backup when nobody is online:
- Farms/machines running in spawn chunks or other loaded chunks produce items.
- Nobody is online now, but someone was online between now and the previous backup.

Right now, you can use restic to save storage space when there are no changes to the world since the last backup. Restic [deduplicates](
https://restic.readthedocs.io/en/v0.3.3/Design/#backups-and-deduplication) files, so no additional storage is used for parts of the world that have not changed. Could you use restic to achieve what you want?

**Comment by SwiftWinds** [comment]
Ah, I did think of this:

> * Farms/machines running in spawn chunks or other loaded chunks produce items.

But didn't this of this:

> * Nobody is online now, but someone was online between now and the previous backup.

I would imagine this could be checked for by parsing the logs or something, but that might add unnecessary complexity to the code when Restic solves the problem fine.

Personally, I have unlimited Google Drive storage, so migrating to Restic--although cool--would be unnecessary extra work at this point (also, I see that it creates a large index of small file chunks and, having worked with node_modules on Google Drive before, I'm worried that syncing that many small files could present issues, as mentioned in [this thread](https://forum.restic.net/t/should-we-discourage-users-from-using-google-drive/1740/23)). 

I'll leave this issue open for now if you're still interested in implementing it (feel free to close it if you're not), but I don't think I'll be switching to Restic anytime soon.

Thanks for the quick reply though! :)

**Comment by cgmckeever** [comment]
can you make a checksum and/or the current date/time of the world file and determine if they changed. I dont know if the world just continues to evolve if there is no players .. which would make this idea unrealistic

**Comment by SwiftWinds** [comment]
I took a checksum of two backups taken one hour apart when no one was online, but the checksums were indeed different:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/12981958/121830875-ed0c1300-cc7a-11eb-8f77-f9c541e076de.png">

I'm not that proficient as to how these checksums work, but maybe it's because of minute changes in the chunks rendered (e.g., the spawn chunk) changing the file's contents. Or maybe it's the case that tar.gz'ing the same folder at different times yields different hashes; I'm not really sure.

**Comment by nicolaschan** [comment]
> I see that it creates a large index of small file chunks and, having worked with node_modules on Google Drive before, I'm worried that syncing that many small files could present issues

Restic on Google drive (using the rclone backend) has been fine for me. The first backup takes a long time but the later ones only take a few minutes at most. Maybe your experience will differ, but you could test it out if you're unsure.

> I dont know if the world just continues to evolve if there is no players

The world evolves over time in the [spawn chunks](https://minecraft.fandom.com/wiki/Spawn_chunk). 

> Or maybe it's the case that tar.gz'ing the same folder at different times yields different hashes

[`gzip` includes a timestamp by default](https://serverfault.com/a/110244) so you will get different hashes even if they are the same folder.

**Comment by cgmckeever** [comment]
I think .. but could be wrong .. if the files were the same, the tar would be too and then the checksum would be the same. Easier(ish) way is to see if the timestamp changes of a world file after some time .. if it is, there is writing, and my idea is silly ;)

**Comment by nicolaschan** [comment]
In my experience the file modified timestamps of files in the world do change when the server is running with nobody online. If the server is not running then nothing will change, so maybe your idea applies in this case.

As I mentioned, the compression might not always create an output with the same hash even if given the same inputs. So we would want to look at the actual world and compare with the world extracted from the last backup.

Right now I think this would be unnecessary complexity since it would only apply when the server is not running. And even then this situation is covered by restic. But let me know if anyone has a compelling need for this feature that we haven't addressed :)

**Comment by SwiftWinds** [comment]
Ah, thanks for the clarification, and good to hear that Restic works well for you. :)

For now, the full backups of the world, while inefficient, are simple and I have unlimited storage. I'll definitely consider using Restic for future servers though, thanks again!

**Comment by SwiftWinds** [comment]
Btw, do you prune your Restic backup as part of your cronjob (maybe like once a month)? Or does your script do it automatically? Or do you just not worry about pruning?

Asking for future reference since I will likely use Restic in future servers that require backups.

**Comment by nicolaschan** [comment]
The script can handle pruning using the same options as pruning for tar file backup. Personally, I didn't prune since I also had unlimited storage.

**Comment by SwiftWinds** [comment]
Got it. Thanks!

**Comment by SwiftWinds** [comment]
If you also have unlimited storage, why do you use Restic? Isn't tar.gz a simple and surefire way of keeping your backups safe? Or does Restic have some extra, sought-after features? I use google-drive-ocamlfuse to mount my Google Drive, and I set it to be the folder target of your script. Works great!

**Comment by nicolaschan** [comment]
As I understand it, using restic saves bandwidth since restic only sends the changes each time. I use the rclone backend with restic. I'm not sure if putting a restic repo directly in a fuse mount will perform as well.

**Comment by SwiftWinds** [comment]
Ah, I see. I run my servers on GCP and a little known perk of GCP is that all network egress and ingress to Google services (Google Drive included) is free, so saving bandwidth isn't really my concern. And yeah, I agree, if I were to use Restic, it seems much safer to use Rclone than a FUSE mount.

**Comment by SwiftWinds** [comment]
Ah, BTW, I recently migrated to Restic and Rclone (I was facing memory leak issues with google-drive-ocamlfuse) and I must say, the process was super quick and easy, and I'm impressed by Restic's ability to make super tiny backups when little has changed (~1 MB when nobody is online) and reasonable backups when players are active (~200 MB added and ~200 MB deleted). Thanks again for the suggestion! 😄

**Comment by nicolaschan** [comment]
Glad to hear it's working well!
