### ISSUE TITLE
Why can't I add Microsoft accounts?

### ISSUE THREAD

**Issue by perdakovich** [nicolaschan/minecraft-backup#29]
In Prism Launcher you can add Microsoft accounts:
![image](https://user-images.githubusercontent.com/89806596/215199311-1481a9b2-94d9-422b-93cb-b5352734c4a9.png)

In PollyMC you can not:
![image](https://user-images.githubusercontent.com/89806596/215202208-b7df088e-8e00-481e-9cc3-ea337136cfbc.png)

Why? 
Your launcher is good, I'll even say the best for me, but I use both ely.by and the Microsoft accounts.
Also you can't install Prism and Polly at same time, so I can't use polly for ely.by and prism for license.

**Comment by polarfoxDev** [comment]
@goosegit11 but this repository is not PollyMC, it's just a backup script 😄

**Comment by perdakovich** [comment]
uhh I have no idea what happened there sorry :-)
