### ISSUE TITLE
Confusing Setup Process

### ISSUE THREAD

**Issue by okschlatter** [nicolaschan/minecraft-backup#3]
The code snippet in your README file doesn't match the code in backup.sh. I followed the README comments instead of the comments in the actual code, and I ended up backing up my entire server directory instead of just the world directory. Big headaches figuring out what went wrong because it's such a little detail and I was going too fast. Please fix the README so that there is less confusion in the future.

**Comment by nicolaschan** [comment]
Great point. Yep, it was out of date. I've updated it in commit 2467e1e. Feel free to repoen this issue or open a new one to let me know if anything is still unclear or incorrect.
