### ISSUE TITLE
backup.sh: 66: backup.sh: Syntax error: Bad function name

### ISSUE THREAD

**Issue by Everglase** [nicolaschan/minecraft-backup#7]
I'm getting the following error:
backup.sh: 66: backup.sh: Syntax error: Bad function name

Running on Ubuntu 18.04
Script attached.

[backup.zip](https://github.com/nicolaschan/minecraft-backup/files/4824383/backup.zip)

**Comment by nicolaschan** [comment]
Make sure you're using `bash` and not `sh` to run the script.

**Comment by nicolaschan** [comment]
Closing, but feel free to reopen or submit again if this didn't resolve your issue.
