### ISSUE TITLE
Problem with crontab

### ISSUE THREAD

**Issue by askrealcookie** [nicolaschan/minecraft-backup#9]
Hey! This is script is soo lifesaver! However I have to make backups by typing command manually. I am new to linux and I had a lot of problems with cron, even after reading ton of tutorials or smth similar.

My configuration looks like
```
##
#commented section
##

0 * * * * /home/backup.sh
```

But what I get every hour is: `Backup was not saved!` information. I read something about PATH in cron in readme.md, but I can't really understand what do you mean by that(Imma add that English is not my native language). It would be really nice if you could share example crontab configuration file!

**Comment by gekkone** [comment]
Hi, add arguments (argument information can be obtained by running backup.sh —help). 

Here's a simple example of what you should get: “/path/backup.sh -i /path/to/worldDir -o /path/to/backupsDir -s ScreenName -m 16 -c”

**Comment by askrealcookie** [comment]
Ohhh, I thought assigning values in script file should work! Thanks for awesome script and help! (and sorry for stupid question 😳)
